/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Pemesanan extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    private String sql;
    private String kode, nama, id;
    private int hrg, jumlah, total_harga;
    
    /**
     * Creates new form Pemesanan
     */
    public Pemesanan() {
        initComponents();
        con = koneksi.koneksiDB();
        ShowData(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pesanbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        no_trans = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nm_kue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jmlh = new javax.swing.JTextField();
        menu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kd_brg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BAKERY & CAKE");

        tabel_data.setBackground(java.awt.Color.pink);
        tabel_data.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Kue", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_data);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Barang & Harga");

        pesanbt.setBackground(java.awt.Color.pink);
        pesanbt.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        pesanbt.setText("Pesan Sekarang");
        pesanbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesanbtMouseClicked(evt);
            }
        });
        pesanbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanbtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("No Transaksi");

        no_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_transActionPerformed(evt);
            }
        });
        no_trans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_transKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel4.setText("Nama Kue");

        nm_kue.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel5.setText("Harga");

        harga.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah Pembelian");

        jmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmlhKeyReleased(evt);
            }
        });

        menu.setBackground(java.awt.Color.pink);
        menu.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setText("Total");

        total.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel8.setText("Kode Barang");

        kd_brg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kd_brgKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nm_kue, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(harga)
                            .addComponent(jmlh)
                            .addComponent(no_trans)
                            .addComponent(total)
                            .addComponent(kd_brg))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pesanbt)
                        .addGap(236, 236, 236))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(menu)
                        .addGap(278, 278, 278))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(no_trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nm_kue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jmlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addComponent(pesanbt)
                .addGap(18, 18, 18)
                .addComponent(menu)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesanbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanbtActionPerformed
        // TODO add your handling code here:
        id = String.valueOf(no_trans.getText());
        kode = String.valueOf(kd_brg.getText());
        nama = String.valueOf(nm_kue.getText());
        hrg = Integer.parseInt(harga.getText());
        jumlah = Integer.parseInt(jmlh.getText());
        total_harga = Integer.parseInt(total.getText());
       
        pesan.setId(id);
        pesan.setKode(kode);
        pesan.setNama(nama);
        pesan.setHarga(hrg);
        pesan.setJumlah(jumlah);
        pesan.setTotal(total_harga);
        try{
            sql = "INSERT INTO pemesanan (no_transaksi, kode_barang, nama_kue, harga, jumlah, total)value" + "('"+ id +"','"+ kode +"','"+ nama +"', '"+ hrg +"','"+ jumlah +"','"+ total_harga + "')";
            st = con.createStatement();
            st.execute(sql);
            Clear();
            JOptionPane.showMessageDialog(null, "Anda Berhasil Melakukan Pemesanan ");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Silahkan Coba Lagi");
        }
    }//GEN-LAST:event_pesanbtActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void no_transKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_transKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_no_transKeyReleased

    private void jmlhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlhKeyReleased
        // TODO add your handling code here:
        String prc = harga.getText();
        String qty = jmlh.getText();
        double prcs = Double.parseDouble(prc);
        double qtys = Double.parseDouble(qty);
        DecimalFormat df = new DecimalFormat("#.##");
        total.setText(df.format(prcs*qtys));
    }//GEN-LAST:event_jmlhKeyReleased

    private void pesanbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesanbtMouseClicked

    }//GEN-LAST:event_pesanbtMouseClicked

    private void kd_brgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kd_brgKeyReleased
        // TODO add your handling code here:
        kode = kd_brg.getText();
        int enter = evt.getKeyCode();
        if(enter==10){
            try{
                sql = "SELECT * FROM data " + "WHERE kode_barang='"+kode+"'";
                st=con.createStatement();
                rs=st.executeQuery(sql);
                while(rs.next()){
                    nm_kue.setText(rs.getString("nama_kue"));
                    harga.setText(rs.getString("harga"));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data Tidak Ada / Tidak Ditemukan" +e.getMessage());
                //nm_brg.requestFocus();
            }
        }
    }//GEN-LAST:event_kd_brgKeyReleased

    private void no_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_transActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlh;
    private javax.swing.JTextField kd_brg;
    private javax.swing.JButton menu;
    private javax.swing.JTextField nm_kue;
    private javax.swing.JTextField no_trans;
    private javax.swing.JButton pesanbt;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void ShowData(String sql) {
        DefaultTableModel data = new DefaultTableModel();
        data.addColumn ("Kode Barang");
        data.addColumn ("Nama Kue");
        data.addColumn("Harga");
        try{
            st=con.createStatement();
            rs = st.executeQuery("SELECT * from data");
            while(rs.next())
                data.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                });
            tabel_data.setModel(data);
                    }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Memuat KeDatabase \n Aktifkan Database Sebelum Memulai");
        }
   
    }

    private void Clear() {
        no_trans.setText("");
        kd_brg.setText("");
        nm_kue.setText("");
        harga.setText("");
        jmlh.setText("");
        total.setText("");
    }
}
